data_config:
  train_file: msc_train_dialogsum_new_prompt_ab_memory.json
  val_file: msc_test_dialogsum_new_prompt_ab_memory.json
  test_file: msc_test_dialogsum_new_prompt_ab_memory.json
  num_proc: 16
max_input_length: 2048
max_output_length: 64
training_args:
  # see `transformers.Seq2SeqTrainingArguments`
  output_dir: /data1/chyang/new_prompt_dialogsum_ab_memory
  max_steps: 25000
  # settings for data loading
  per_device_train_batch_size: 4
  dataloader_num_workers: 4
  remove_unused_columns: false
  # settings for saving checkpoints
  save_strategy: steps
  save_steps: 1000
  # settings for logging
  log_level: info
  logging_strategy: steps
  logging_steps: 20
  # settings for evaluation
  per_device_eval_batch_size: 16
  evaluation_strategy: steps
  eval_steps: 500
  # settings for optimizer
  # learning_rate: 1e-4
  # adam_epsilon: 1e-6
  # uncomment the following line to detect nan or inf values
  # debug: underflow_overflow
  predict_with_generate: true
  # see `transformers.GenerationConfig`
  generation_config:
    max_new_tokens: 256
  # set your absolute deepspeed path here
  #deepspeed: ds_zero_2.json
  # set to true if train with cpu.
  use_cpu: false
peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
